apiVersion: apps/v1
kind: Deployment
metadata:
  name: dob-facts-frontend
  namespace: dob-facts-app
  labels:
    app: dob-facts-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dob-facts-frontend
  template:
    metadata:
      labels:
        app: dob-facts-frontend
    spec:
      containers:
      - name: frontend
        image: #__#IMAGE_NAME#__#:#__#IMAGE_TAG#__#
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        envFrom:
        - configMapRef:
            name: dob-facts-config
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: acr-cred
---
apiVersion: v1
kind: Service
metadata:
  name: dob-facts-frontend-service
  namespace: dob-facts-app
  labels:
    app: dob-facts-frontend
spec:
  selector:
    app: dob-facts-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
