apiVersion: v1
kind: Namespace
metadata:
  name: dob-facts-app
  labels:
    name: dob-facts-app

---
apiVersion: v1
kind: Secret
metadata:
  name: ACR-secret
  namespace: dob-facts-app
type: Opaque
data:
  username: #__#ACR_USERNAME#__#    # base64 encoded value of "admin"
  password: #__#ACR_PASS#__#  # base64 encoded value of "password"
