apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-config
  namespace: temporal
data:
  docker.yaml: |
    persistence:
      default:
        driver: "postgres"
        host: "postgres.temporal.svc.cluster.local"
        port: 5432
        user: "temporal"
        password: "temporal"
        database: "temporal"
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: "1h"
      visibility:
        driver: "postgres"
        host: "postgres.temporal.svc.cluster.local"
        port: 5432
        user: "temporal"
        password: "temporal"
        database: "temporal_visibility"
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: "1h"

  config_template.yaml: |
    log:
      stdout: true
      level: "info"

    persistence:
      defaultStore: default
      visibilityStore: visibility
      numHistoryShards: 4
      datastores:
        default:
          sql:
            pluginName: "postgres"
            databaseName: "temporal"
            connectAddr: "postgres.temporal.svc.cluster.local:5432"
            connectProtocol: "tcp"
            user: "temporal"
            password: "temporal"
        visibility:
          sql:
            pluginName: "postgres"
            databaseName: "temporal_visibility"
            connectAddr: "postgres.temporal.svc.cluster.local:5432"
            connectProtocol: "tcp"
            user: "temporal"
            password: "temporal"
