name: Frontend Deployment

on: workflow_dispatch

permissions:              
  id-token: write          # required for OIDC federation
  contents: read   
  
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses:  actions/checkout@v4

        # Login to ACR
    - name: ACR Login
      run: docker login acrtodoappdev01.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

    # Build and Push Docker Image
    - name: Build and Push
      run: |
        ACRNAME=acrtodoappdev01
        IMAGENAME=dob_facts_ui
        IMAGE=$ACRNAME.azurecr.io/dob_facts
        TAG=${{ github.run_number }}   # you can also use ${{ github.sha }} for commit hash or 'latest'

        echo "Building image $IMAGE:$TAG"
        docker build -t $IMAGE/$IMAGENAME:$TAG -f Dockerfile.frontend .

        echo "Pushing image $IMAGE:$TAG"
        docker push $IMAGE/$IMAGENAME:$TAG

          echo "Pushed image $IMAGE:$TAG to $ACRNAME"
    

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'


    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: rg-todoapp-dev
        cluster-name: aks-todoapp-dev01

    - name: Deploy Frontend to Kubernetes
      run: |
       kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
         kubectl apply -f k8s/ingress.yaml
