name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0 


      #setup JDK for sonar scanner beacuse sonarQube is java base application  its need JDK to run sonar scanner
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'


      # Setup Python for backend
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          cd backend
          pip install -r requirements.txt

      # Run backend unit tests with coverage
      - name: Run backend unit tests with coverage
        run: |
          export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}
          cd backend
          pip install coverage pytest pytest-cov
          coverage erase
          mkdir -p test-reports
          PYTHONPATH=. coverage run --source=. -m pytest test_server.py --junitxml=test-reports/pytest-report.xml
          coverage report --fail-under=70
          coverage xml -i
          coverage html
          ls -la  # Debug: List files to verify reports were generated

      # Setup Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend deps
        run: |
          npm install
          npm run build

      # Run frontend unit tests with coverage
      - name: Run frontend unit tests with coverage
        run: |
          npm install --save-dev jest @types/jest @testing-library/react @testing-library/jest-dom
          npm test -- --coverage --coverageReporters=lcov --coverageReporters=text-summary
          ls -la coverage  # Debug: List coverage directory contents

      # ✅ SonarQube Scan using GitHub Action updated this
      - name: Run SonarQube Scan
        run: |
          docker run --rm \
            -e SONAR_HOST_URL=http://4.187.226.1:9000 \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -v ${{ github.workspace }}:/usr/src \
            sonarsource/sonar-scanner-cli:latest \
            -Dsonar.projectKey=dob-fact \
            -Dsonar.sources=src,backend \
            -Dsonar.tests=__tests__,backend \
            -Dsonar.test.inclusions=**/*test.ts,**/*test.tsx,**/test_*.py \
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info \
            -Dsonar.python.coverage.reportPaths=./backend/coverage.xml \
            -Dsonar.python.xunit.reportPath=./backend/test-reports/pytest-report.xml \
            -Dsonar.inclusions=**/*.ts,**/*.tsx,**/*.py \
            -Dsonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/__pycache__/**,**/coverage/**,**/*.config.*,**/*.test.ts,**/*.test.tsx,**/test_*.py \
            -Dsonar.javascript.coveragePlugin=lcov \
            -Dsonar.language=ts,python \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.host.url=http://4.187.226.1:9000 \
            -Dsonar.verbose=true

